services:
- enabled: true
  host: 127.0.0.1
  name: ${{ env "DECK_SERVICE_TAG" }}-service
  port: 65535
  protocol: https
  routes:
  - hosts:
    - test.demofor.fun
    name: dummy-route
    paths:
    - /.well-known/acme-challenge
    protocols:
    - http