services:
  - name: ${{ env "DECK_SERVICE_TAG" }}-service
    enabled: true
    url: http://echo
    routes:
      - name: ${{ env "DECK_SERVICE_TAG" }}-test-route
        hosts:
          - ${{ env "DECK_PROXY_HOSTNAME" }}
        paths:
          - /echo
      - name: ${{ env "DECK_SERVICE_TAG" }}-basic-auth-route
        hosts:
          - ${{ env "DECK_PROXY_HOSTNAME" }}
        paths:
          - /basic
      - name: ${{ env "DECK_SERVICE_TAG" }}-key-auth-route
        hosts:
          - ${{ env "DECK_PROXY_HOSTNAME" }}
        paths:
          - /key