name: Offboard APIs checks

on:
  pull_request:
    branches:
      - offboard
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  offboard-services-configs-review:
    name: Check offloading Kong configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folders: ["catch-all"]
        env: [dev]
        include:
          - env: dev
            ADMIN_API_URL: ${{ secrets.DEV_ADMIN_API_URL }}
            ADMIN_API_AUTH_HEADER: ${{ secrets.DEV_ADMIN_API_AUTH_HEADER }}
    env:
      DECK_VERSION: ${{ env.DECK_VERSION }}
      DECK_SERVICE_TAG: ${{ matrix.folders }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install Deck
        run: |
          curl -sL https://github.com/Kong/deck/releases/download/v${DECK_VERSION}/deck_${DECK_VERSION}_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/
      - name: Check Control plane is reachable
        run: |
          deck ping \
            --headers "${{ matrix.ADMIN_API_AUTH_HEADER }}" \
            --kong-addr "${{ matrix.ADMIN_API_URL }}"
      - name: Review Kong entities associated to $DECK_SERVICE_TAG-svc tag
        run: |
          deck dump \
            --headers "${{ matrix.ADMIN_API_AUTH_HEADER }}" \
            --kong-addr "${{ matrix.ADMIN_API_URL }}" \
            --select-tag $DECK_SERVICE_TAG-svc \
            --output-file -